version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: agregio_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agregio
    ports:
      - '5432:5432'
    volumes:
      - ~/.cache/database/agregio:/var/lib/postgresql/data

volumes:
  db:
    driver: local